name: Checkout Action

on:
  push:
    branches:
      - main

jobs:
  read-file:
    runs-on: ubuntu-latest
    name: Read text file using checkout action

    steps:
      - name: Checkout file
        uses: actions/checkout@v3

      - name: Show current directory
        run: pwd

      - name: List files in the repo
        run: ls -R  

      - name: Read file
        run: cat ./1.Checkout_Action/test.txt