name: Access Context from Multiple Steps

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Generate a greeting
        id: step_greet
        run: echo "greeting=Hello" >> $GITHUB_OUTPUT

      - name: Step 2 - Generate a name
        id: step_name
        run: echo "name=World" >> $GITHUB_OUTPUT

      - name: Step 3 - Combine greeting and name
        id: step_combine
        run: echo "full_message=${{ steps.step_greet.outputs.greeting }} ${{ steps.step_name.outputs.name }}" >> $GITHUB_ENV

      - name: Step 4 - Display the full message
        run: |
          echo "Final Message: $FULL_MESSAGE"
        env:
          FULL_MESSAGE: ${{ steps.step_greet.outputs.greeting }} ${{ steps.step_name.outputs.name }}
