name: Access workflow context example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Context
        run: |
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Repository Name: ${{ github.repository }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
