name: Shell Script Example

on:
  push:
    branches:
      - main

jobs:
  shell-scripting:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run shell script
        run: |
          echo "Hello from shell script!"
          name="Malinda"
          echo "Welcome, $name"
          echo "List of files:"
          ls -la
