name: Working with Variables

env:
  GLOBAL_VAR: "This is a global variable"
  ANOTHER_VAR: "This is another global variable"

on:
  push:
    branches:
      - main

jobs:
  global-var-job:
    runs-on: ubuntu-latest
    name: Global Variable Job

    steps:
      - name: Print Global Variable
        run: |
          echo "Global Variable: $GLOBAL_VAR"
          echo "Another Global Variable: $ANOTHER_VAR"

  job-with-env:
    runs-on: ubuntu-latest
    name: Job with Environment Variables
    env:
      MY_JOB_VAR: "This is an environment variable"
      ANOTHER_JOB_ENV_VAR: "This is another environment variable"

    steps:
      - name: Print Environment Variable

        run: |
          echo "Job Environment Variable: $MY_JOB_VAR"
          echo "Another Job Environment Variable: $ANOTHER_JOB_ENV_VAR"
          echo "Global Variable: $GLOBAL_VAR"
          echo "Another Global Variable: $ANOTHER_VAR"
