name: Var and Secret Example

on:
  push:
    branches:
      - main

jobs:
  var-job:
    runs-on: ubuntu-latest
    name: Variable Job

    steps:
      - name: Print Variables
        run: |
          echo "Var example: $MY_VAR"
        env:
          MY_VAR: ${{vars.MY_VAR}}

  secret-job:
    runs-on: ubuntu-latest
    name: Secret Job

    steps:
      - name: Print Secrets
        run: |
          echo "Secret Variable: $MY_SECRET"
        env:
          MY_SECRET: ${{secrets.MY_SECRET}}
